### Site Settings ###
title               : Sangyeon Lee
description         : >-
                      Welcome to my homepage.<br><br>
                      <strong><em>Projects</em></strong> contain my small research conducted out of curiosity.<br>
                      <strong><em>Learning Note</em></strong> contains my records of learned knowledge.<br>
                      <strong><em>About</em></strong> contains my brief information.
                    # [GitHub] "", [LoopBack] "/portfolYOU"
baseurl             : ""                               
                    # [GitHub] syleemj23/syleemj23.github.io, [LoopBack] YoussefRaafatNasry/portfolYOU
repository          : syleemj23/syleemj23.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Sangyeon Lee
                    # [GitHub] /imgs/MyPicture.jpg, [LoopBack] /portfolYOU/imgs/MyPicture.jpg
  image             : /imgs/MyPicture.jpg
# behance           : your_username
# dribbble          : your_username
  email             : syleemj23@gmail.com
# facebook          : your_username
  github            : syleemj23
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : syleemj23
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  
### Disqus ###
disqus:
  shortname: syleemj23-github-io                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
